- .github/workflows/main.yml
- BUILD.bazel
- README.md
- quality/BUILD.bazel
- rules/quality.bzl
This PR:
- Reorganizes the lint rules and puts them in a separate BUILD file to consolidate similar targets and not pollute the top-level BUILD file.
- Sligns the linter/formatter Bazel target labels to match the convention <tool>_{check,fix} as is used in the main opentitan repository.
This partially addresses #9.
>  [quality] move lint targets to separate BUILD file and align target labels

- src/ate/ate_api.h
- src/ate/ate_dll.cc
- src/proto/device_id.proto
- src/proto/device_testdata.go
- src/proto/validators.go
- src/proto/validators_test.go
- src/proxy_buffer/proto/validators_test.go
- src/proxy_buffer/store/db.go
- src/proxy_buffer/store/db_test.go
This updates the device ID format to match the spec published on the OpenTitan website: https://opentitan.org/book/doc/security/specs/identities_and_root_keys/#device-identifier . In doing so, this also simplifies the device ID layout, removing an un-needed `DeviceType` nested message type. Additionally, this removes OpenTitan lifecycle states that are not supported in current OpenTitan hardware.
> [device_id] update device ID format to match OpenTitan silicon

- src/proto/BUILD.bazel
- src/proto/device_testdata.go
- src/proto/validators.go
- src/proto/validators_test.go
- src/proxy_buffer/proto/BUILD.bazel
- src/proxy_buffer/proto/validators_test.go
This fixes #15 by consolidating all common proto validation test data into a single library.
> [test] consolidate test data into one library

- src/pa/proto/pa.proto
- src/pa/services/pa.go
- src/proto/crypto/cert.proto
This partially addresses #4 by adding RPC function stubs for:
1. endorsing cert payloads from OT devices (during personalization),
2. generating LC tokens (in raw and hashed forms), and
3. generating wafer authentication secrets.
> [pa] add RPC stubs for endorsing certs and generating LC/WAS tokens

- docs/spm.md
- run_integration_tests.sh
- src/pk11/kdf.go
- src/spm/spmutil.go
This adds KDF seed loading subcommands to support the KDF operations that will be used to generate OpenTitan Earlgrey LC tokens and Wafer Auth Secrets during provisioning.
This partially addresses #4.
This fixes #20.
> [spmutil] add KDF seed loading subcommands

- config/dev/spm/sku_auth.yml
- config/dev/spm/sku_tpm_1.yml
- src/pa/loadtest.go
- src/pa/pa_server.go
- src/pa/proto/pa.proto
- src/spm/BUILD.bazel
- src/spm/services/se.go
- src/spm/services/spm.go
The `./run_integration_tests.sh` script was failing for many reasons, and this fixes two issues:
1. adding a reference SKU authorization YAML config file with a test authorization password to revive the `pa/loadtest.go` program, and
2. default to disabling the registry buffer until #24 can be addressed.
This partially addresses #17.
> [tests,pa,spm] add/fix configurations to enable running integration tests

- config/dev/deploy.sh
- run_integration_tests.sh
Previously, `./run_integration_tests.sh` would build a release tarball of all the provisioning binaries, along with container images containing each provisioning binary, and then unpack the binaries into the deployment staging area, even if only the containers were run. This was slow when debugging because compressing and uncompressing binaries (that are not even used) is slow.
This adds a `-c` mode to the `./run_integration_tests.sh` to only build an deploy the container images to save time when debugging.
Additionally, a `-d` (debug) mode is added that prevents the containers from being torn down on script exit to enable debugging test failures.
> [tests] and different operation modes to integration testing script

- .github/workflows/main.yml
- config/dev/spm/sku_auth.yml
- src/pa/BUILD.bazel
- src/pa/loadtest.go
- src/pa/services/BUILD.bazel
- src/pa/services/pa.go
- src/transport/auth_service/auth_interceptor.go
- src/transport/auth_service/auth_service.go
This updates the PA and auth_controller to accept a userID from the client instead of always defaulting to using the client IP address as the user ID. This way we can test several sessions eminating from the same host.
Additionally, this updates the loadtest to:
1. send a userID to the PA upon session initialization and closing, and
2. save session auth tokens received from the PA during InitiSession calls, and forward them back to the server on calls to CreateKeyAndCert, to authorize invoking these RPCs.
With these changes, we can now execute the PA loadtest successfully. Therefore, the last commit in this PR also adds the integration tests (i.e., PA loadtest) to the presubmit CI configuration.
> [pa,auth,loadtest] fix PA token authentication mechanism and loadtest

- src/spm/services/se.go
- src/spm/services/se_pk11.go
- src/spm/services/se_pk11_test.go
This adds a wrapper function to the Secure Element (SE) interface to derive symmetric keys from pre-loaded secret seeds on the SE. This function will back the DerriveSymmetricKey RPC available from the ProvisioningAppliance. This partially addresses #4.
> [se] add function to generate symmetric keys

- .github/workflows/main.yml
- run_integration_tests.sh
- util/containers/deploy_test_k8_pod.sh
This adds a script that builds, deploys, and initializes the PA / SPM containers locally for testing. Additionally, we update the `run_integration_tests.sh` script to reuse the same code as the new deployment script.
> [util] add script to deploy containers for testing

- WORKSPACE
- rules/repo.bzl
- third_party/bazel/repos.bzl
- third_party/crt/repos.bzl
- third_party/docker/repos.bzl
- third_party/go/repos.bzl
- third_party/google/repos.bzl
- third_party/lint/repos.bzl
- third_party/lowrisc/repos.bzl
- third_party/protobuf/repos.bzl
- third_party/softhsm2/repos.bzl
This updates all `http_archive` rules to use a new macro, `http_archive_or_local`, which enables using a local version of the dependency instead of a remote HTTP archive. This is useful when debugging issues with dependencies.
> [bazel] define `http_archive_or_local` macro and use it

- run_integration_tests.sh
- src/ate/ate_api.h
- src/ate/ate_client.cc
- src/ate/ate_client.h
- src/ate/ate_dll.cc
- src/ate/ate_main.cc
- src/ate/test_programs/BUILD.bazel
- src/ate/test_programs/cp.cc
This adds reference CP test program boilerplate code. This partially addresses #6.
> [ate,cp] add reference CP test program boilerplate

- quality/BUILD.bazel
- rules/quality.bzl
- rules/scripts/include_guard.sh
- src/ate/ate_api.h
- src/ate/ate_client.h
- src/testing/test_helpers.h
- src/transport/service_credentials.h
- src/version/version.h
- util/BUILD.bazel
- util/fix_include_guard.py
This adds a CI check for include guards in C/C++ header files. Additionally this fixes existing include guards in the code base to be style guide compliant.
> [quality] add C/C++ header file nclude guard check

- .bazelrc
- WORKSPACE
- third_party/bazel/deps.bzl
- third_party/crt/repos.bzl
- third_party/google/repos.bzl
- third_party/lowrisc/repos.bzl
This adds the lowrisc_opentitan repository as a Bazel dependency in order to build opentitanlib as a dependency for an FPGA DUT shim layer that will be used for running provisioning flow tests in the lab.
Additionally, this adds skylib, rules_python, and rules_rust as external dependencies, as these are also required for building opentitanlib.
Lastly, this updates the CRT and misc_linters dependencies, as this is required to build opentitanlib as well.
> [bazel] add lowrisc_opentitan as a dependency

- WORKSPACE
- third_party/lowrisc/repos.bzl
Several python dependencies were updated in the `lowrisc_opentitan` bazel repo recently lowRISC/opentitan:#26090,#26091,#26092. This updates this repo to pull in these change which impact the ability to perform airgapped bazel builds.
> [bazel] update lowrisc_opentitan repo dep

- third_party/lowrisc/ot_bitstreams/BUILD.bazel
- third_party/lowrisc/ot_bitstreams/build-ot-bitstreams.sh
- third_party/lowrisc/repos.bzl
This partially addresses #5 by updating the `lowrisc_opentitan` dep (to take advantage of recent changes that enable using on opentitanlib as a dep) and checking in bitstreams to use for E2E provisioning testing.
> [bazel] update lowrisc_opentitan and check-in bitstreams

- .github/actions/prepare-env/action.yml
- .github/workflows/create_release.yml
- .github/workflows/main.yml
- WORKSPACE
- apt-requirements.txt
- run_integration_tests.sh
- src/ate/test_programs/BUILD.bazel
- src/ate/test_programs/cp.cc
- src/ate/test_programs/dut_lib/BUILD.bazel
- src/ate/test_programs/dut_lib/dut_lib.cc
- src/ate/test_programs/dut_lib/dut_lib.h
- src/ate/test_programs/otlib_wrapper/BUILD.bazel
- src/ate/test_programs/otlib_wrapper/src/lib.rs
- third_party/lowrisc/provisioning_exts/BUILD.bazel
- third_party/lowrisc/provisioning_exts/cfg.bzl
- util/airgapped_builds/prep-bazel-airgapped-build.sh
- util/airgapped_builds/test-airgapped-build.sh
The dut_lib will be used to interface a test program with a DUT backend.
This will enable E2E testing with FPGAs or real silicon.
This initial version loads a bitstream onto an FPGA using opentitanlib.
This depends on #51, only review the last two commits.
> [dut_lib] add initial dut_lib boilerplate and otlib_wrapper

- src/pa/proto/pa.proto
- src/proto/device_id.proto
- src/proxy_buffer/proto/proxy_buffer.proto
This udpates the device ID namespace to be more specific to the OT project. Additionally, remove CRC from device ID field.
> [proto] update DeviceId protos namespace

- src/proto/BUILD.bazel
- src/proto/registry_record.proto
This message will serve as the input to the various downstream SKU-owner registry service(s).
> [proto] add registry record proto message

- src/proto/registry_record.proto
This contains two fixes to the RegistryRecord message:
1. we add a "sku" string field to make it easier to route different records to various backend customer registries, and
2. encode the version field as a variable length uint32.
> [proto] adjust RegistryRecord proto based on feedback

- src/proto/BUILD.bazel
- src/proto/device_id_utils.go
- src/proto/validators.go
This contains two commits that:
1. adds a utility for converting a DeviceID proto object to a hexstring, and
2. adds a Bazel proto build target for the RegistryRecord proto message.
> [bazel,utils] add missing build target and DeviceID to string conversion utility

- src/pa/proto/pa.proto
- src/pa/services/BUILD.bazel
- src/pa/services/pa.go
- src/proto/BUILD.bazel
- src/proto/device_id.proto
- src/proto/device_id_utils.go
- src/proto/device_testdata.go
- src/proto/validators.go
- src/proto/validators_test.go
- src/proxy_buffer/pb_server_integration_test.go
- src/proxy_buffer/proto/BUILD.bazel
- src/proxy_buffer/proto/proxy_buffer.proto
- src/proxy_buffer/proto/validators.go
- src/proxy_buffer/proto/validators_test.go
- src/proxy_buffer/services/BUILD.bazel
- src/proxy_buffer/services/proxybuffer.go
- src/proxy_buffer/services/proxybuffer_test.go
- src/proxy_buffer/store/BUILD.bazel
- src/proxy_buffer/store/db.go
- src/proxy_buffer/store/db_test.go
This refactors the proto that is sent to the ProxyBuffer to register an OT device. The RegistryRecord proto was added in a previous commit to simplify the interface to downstream registry services. This is the first step towards enabling a PA shim layer for translating device records for sending to various downstream registry services. 
Note: this relies on #58, only review the last commit.
> [proxy_buffer] refactor registration proto

- config/dev/containers/provapp.yml
- config/dev/deploy.sh
- release/BUILD.bazel
- util/containers/deploy_test_k8_pod.sh
During deployment of the provisioning infrastructure, also launch the proxybuffer and etcd containers. This is the first step before connecting the PA to the ProxyBuffer and testing E2E.
> [proxybuffer] launch proxybuffer and etcd containers

- go.mod
- third_party/go/deps.bzl
- third_party/go/repos.bzl
Update build dependencies:
1. rules_go: 0.41.0
2. gazelle: 0.35.0
3. golang: 19.1
Update golang packages:
1. golang.org/x/crypto: v0.23.0
2. golang.org/x/tools: v0.10.0
> [golang] Update dependencies.

- config/dev/containers/provapp.yml
- go.mod
- src/proxy_buffer/BUILD.bazel
- src/proxy_buffer/pb_server.go
- src/proxy_buffer/store/BUILD.bazel
- src/proxy_buffer/store/filedb.go
- src/proxy_buffer/store/filedb_test.go
- third_party/go/deps.bzl
This change introduces the `filedb` module which implements a sqlite database backend with the gorm ORM library.
The `pb_server` was updated to use `filedb` as the backend. The `etcd` backend will be removed in a follow-up change.
> [proxy_buffer] Add support for sqlite backend.

- src/ate/ate_api.h
- src/ate/ate_client.cc
- src/ate/ate_client.h
- src/ate/ate_client_test.cc
- src/ate/ate_dll.cc
This change adds the following functions to the ate_api.h library:
1. `AllocateDeriveSymmetricKeyResponse`: Allocates memory for a `DeriveSymmetricKeyResponse` call.
2. `FreeDeriveSymmetricKeyResponse`: Releases the memory allocated by `AllocateDeriveSymmetricKeyResponse`. This function must be called after the caller is done processing the data.
3. `DeriveSymmetricKeys`: Calls the provisioning appliance backend to request symmetric keys. The function performs the conversion from C++ C data structures.
The `ate_dll` implementation uses C data structures to be able to be integrated with older compilers with limited C++ support.
> [ate] Add `DeriveSymmetricKeys` call.

- src/ate/ate_api.h
- src/ate/ate_dll.cc
Simplify `DeriveSymmetricKeys` call to allow the caller to allocate memory in the stack for the request and response parameters. As a result, this change removes the `AllocateDeriveSymmetricKeyResponse` and `FreeDeriveSymmetricKeyResponse` functions.
> [ate] Simplify `DeriveSymmetricKeys` call.

- src/ate/BUILD.bazel
- src/ate/ate_api.h
- src/ate/ate_dll.cc
- src/pa/loadtest.go
- src/pa/proto/pa.proto
- src/proto/crypto/BUILD.bazel
- src/spm/services/spm.go
1. Simplify `EndorseCerts()` API in the provisioning appliance service to avoid having to support multiple certs per key associations in the ATE C interface.
2. Implement `EndorseCerts()` in the ATE C library.
> [ate] Add `EndorseCerts()` to ate_api.h.

- src/cert/templates/BUILD.bazel
- src/cert/templates/tpm_test.go
- src/spm/services/BUILD.bazel
- src/spm/services/certloader.go
- src/spm/services/se_pk11_test.go
- src/spm/services/skucfg.go
- src/spm/services/spm.go
Move all SKU configuration settings to their own package to simplify maintenance. Add `PublicKeys`, and `Attributes` settings.
The `Attributes` setting will be used as a key-value store to manage general configuration settings.
> [skucfg] Move SKU settings to their own package.

- src/ate/ate_client_test.cc
- src/ate/ate_dll.cc
- src/pa/loadtest.go
- src/pa/proto/pa.proto
- src/spm/services/se.go
- src/spm/services/se_pk11.go
- src/spm/services/se_pk11_test.go
- src/spm/services/spm.go
This change updates the `GenerateSymmetricKeys` API to add support for
symmetric key generation. Symmetric keys are ephemeral, thus the caller
is required to request a `wrapped_seed` with the result which will
return the seed encrypted by a public key.
Only review the last commit.
> [pa/spm] Add support for deriving new symmetric keys.

- config/dev/spm/sku_tpm_1.yml
- config/prod/containers/provapp.yml
- src/pk11/aes.go
- src/pk11/ecdsa.go
- src/pk11/kdf.go
- src/pk11/kwp_test.go
- src/pk11/object.go
- src/pk11/pk11.go
- src/pk11/rsa.go
- src/pk11/test_support.go
- src/pk11/tool/commands.go
- src/spm/services/se.go
- src/spm/services/se_pk11.go
- src/spm/services/se_pk11_test.go
- src/spm/services/skucfg.go
- src/spm/services/spm.go
- src/spm/spm_server.go
- src/spm/util/certgen.go
The HSM supported attributes and mechanisms should be part of the SKU
configuration. This change removes the `pl11.HSMType` in favor of
applying attributes via `pk11.KeyOptions`, and by defining the key wrap
mechanism via a `skucfg.Config{AttrName}` setting.
In a follow up PR, we are planning to add SKU configurations for the
Luna HSM.
Only review the last commit.
> [pk11] Remove support for HSMType.

- .github/workflows/main.yml
- WORKSPACE
- rules/vendor.bzl
- src/pa/pa_server.go
- src/pa/services/BUILD.bazel
- src/pa/services/pa.go
- src/pa/services/pa_test.go
- src/pa/services/registry_shim/BUILD.bazel
- src/pa/services/registry_shim/registry_shim.go
- src/proxy_buffer/services/BUILD.bazel
- src/proxy_buffer/services/proxybuffer.go
- src/vendor/BUILD.bazel
- src/vendor/WORKSPACE.bazel
- src/vendor/registry_shim/BUILD.bazel
- src/vendor/registry_shim/registry_shim.go
This PR contains several commits that enable a vendor to connect any registry or registry buffer services to the PA, instead of using the ProxyBuffer, by adding a local `vendor_repo` bazel external repo and build configuration setting to override the PA's registry_shim library. With this new mechanism, a vendor can:
1. define a vendor specific bazel repo somewhere on their system, pointed to by the `VENDOR_REPO_DIR` envar, that contains a custom implementation of the `registry_shim` library, and 
2. build the PA using the `--//src/pa/services:use_vendor_shim` bazel bool_flag
> [bazel,pa,registry] add mechansim to enable vendor-specific registries

- src/pa/loadtest.go
Modifies `testOTDeriveSymmetricKeys` to cover symmetric key generation and wrapped seed export.
> [loadtest] Enable coverage for symmetric keygen.

- src/vendor/README.md
This adds a README.md file to describe how to implement a custom `registy_shim` library for the purpose of overriding the `data` field format of the `RegistryRecord` proto to enable integration of the PA with a custom (vendor-specific) Registry Service.
> [doc] add README.md for custom registy_shim development

- src/pa/services/pa_test.go
- src/spm/proto/BUILD.bazel
- src/spm/proto/spm.proto
- src/spm/services/se.go
- src/spm/services/se_pk11.go
- src/spm/services/se_pk11_test.go
- src/spm/services/spm.go
This adds the `EndorseData` RPC to the SPM to enable the SPM to sign RegistryRecord.data payloads before sending them to the registry.
The remaining integration will be completed in a follow up PR.
> [spm] add `EndorseData` RPC

- config/dev/containers/provapp.yml
- config/dev/deploy.sh
- config/dev/env/spm.env
- config/dev/env/spm.yml
This change moves the loadtest `dev` configuration to /var/lib/opentitan/config/dev. This will allow the Thales HSM configuration to be available under /var/lib/opentitan/config/prod.
> [loadtest] Move `dev` to /var/lib/opentitan/config/dev

- config/dev/spm/sku_sival.yml
- src/pa/loadtest.go
- src/spm/services/se.go
- src/spm/services/se_pk11.go
- src/spm/services/se_pk11_test.go
- src/spm/services/spm.go
The `sku_sival.yml` was throwing an unmarshal error which was missed by loadtest.go.
This change fixes the loadtest error as well as the following spm errors:
- Get correct seed label in `se_pk11.GenerateSymmetricKeys`
- Get correct seed wrapping  key in `se_pk11.GenerateSymmetricKeys`
- Add `spm-hsm-id-v0.priv` to the list of `privateKeys` in sku_sival.yml.
> [loadtest] Fix initialization error.

- src/ate/test_programs/cp.cc
- src/ate/test_programs/dut_lib/dut_lib.cc
- src/ate/test_programs/dut_lib/dut_lib.h
- src/ate/test_programs/otlib_wrapper/src/lib.rs
This adds the ability to load SRAM programs into the DUT over JTAG to the dut_lib and otlib_wrapper. This is used by the CP test program to load the CP SRAM binary into the FPGA DUT.
> [dut_lib] add support for loading SRAM binaries over JTAG

- config/prod/BUILD.bazel
- config/prod/containers/provapp.yml
- config/prod/deploy.sh
- config/prod/spm/sku_auth.yml
- config/prod/spm/sku_sival.yml
- release/BUILD.bazel
- run_integration_tests.sh
This change enables the Thales HSM loadtest configuration. The `spm_server` is ran outside a container as a background process to be able to connect to the Thales HSM via ethernet. A follow up change will configure the HSM client to run inside a container.
> [loadtest] Enable loadtest with Thales HSM.

- src/ate/test_programs/cp.cc
- src/ate/test_programs/dut_lib/dut_lib.cc
- src/ate/test_programs/dut_lib/dut_lib.h
- src/ate/test_programs/otlib_wrapper/src/lib.rs
The above functionality was split into two separate functions:
1. the `Create` factory function, and
2. the `DutFpgaLoadBitstream`
functions. This enables the transport to be created when the DutLib is instantiated.
> [dut_lib] split transport init and FPGA bitstream load

- src/ate/test_programs/cp.cc
- src/ate/test_programs/dut_lib/BUILD.bazel
- src/ate/test_programs/dut_lib/dut_lib.cc
- src/ate/test_programs/dut_lib/dut_lib.h
- src/ate/test_programs/otlib_wrapper/BUILD.bazel
- src/ate/test_programs/otlib_wrapper/src/lib.rs
This adds several methods to the DUT lib for interacting with the SPI console including:
1. waiting for a specific message to be received,
2. UJSON message RX, and
3. UJSON message TX.
These primitives will be used to send and receive UJSON messages (a strict subset of JSON, specific to the OpenTitan project) to/from OpenTitan DUTs.
> [dut_lib] add console Wait, RX, and TX methods

- src/spm/services/se_pk11.go
- src/spm/services/se_pk11_test.go
This fixes #112 by returning a key of the requested key size, i.e., the SPM now does the proper truncation after the HMAC-KDF operation instead of requiring the client to perform this operation.
> [spm] fix key size returned by `DeriveSymmetricKey`

- config/dev/spm/sku/sival/01.hsm_offline.hjson
- config/dev/spm/sku/sival/02.hsm_spm.hjson
- third_party/lowrisc/repos.bzl
This brings up supprt for wrap/unwrap mechanism settings for ECDSA and RSA keys in hsmtool.
> [3P] Update OpenTitan to Earlgrey-A2-Provisioning-RC3

- src/pa/proto/pa.proto
- src/pa/services/pa.go
- src/pa/services/pa_test.go
- src/spm/proto/spm.proto
- src/spm/services/spm.go
This adds a GetStoredTokens RPC to the PA/SPM to support retrieving RawUnlock tokens from the SPM during CP. This does not yet implement the RPC, only adds the appropriate protos and template code. This partially addresses #116.
> [pa,spm] add GetStoredTokens RPC

- config/dev/containers/provapp.yml.tmpl
- run_integration_tests.sh
- src/spm/services/spm.go
- src/spm/spm_server.go
Add `--spm_auth_config` CLI flag to spm_server to be able to configure the SKU authentication filename at runtime.
Fixes: https://github.com/lowRISC/opentitan-provisioning/issues/35
> [spm] make SKU authorization file a runtime parameter

- src/pa/loadtest.go
- src/proxy_buffer/store/filedb.go
- src/proxy_buffer/store/filedb_test.go
All queries are based on the device ID which will now be used as the primary key. Also adds a sync state to be used for syncing with external registries.
> [pb] Update schema to match query patterns and add sync state.

- src/proto/device_id.proto
The perso FW hash will be logged during perso flows and should be registered in the database.
> [proto] add perso FW hash field to DeviceData

- apt-requirements.txt
- config/dev/spm/sku/.gitignore
- config/dev/spm/sku/sival/01.hsm_offline.hjson
- config/dev/spm/sku/sival/02.hsm_spm.hjson
- config/dev/spm/sku/sival/ca_int_dice.conf
- config/dev/spm/sku/sival/ca_root.conf
- config/dev/spm/sku/sival/hsm_sku_init.sh
This change adds root and intermediate CA certificates for the SiVal SKU in the `DEV` environment. OpenSSL is used to generate CSRs and final certificates.
The output from the `hsm_sku_init.sh` script is now under the following subdirs:
* `hsm`: HSM intermediate outputs, i.e. wrapped keys exported from the offline HSM and imported into the SPM HSM.
* `ca`: SKU root and intermediate CAs.
* `pub`: SKU public keys.
> [dev] Generate SKU specific CA certificates.

- config/dev/spm/sku/BUILD.bazel
- config/dev/spm/sku/hsm_spm_init.hjson
- config/dev/spm/sku/hsm_spm_init.sh
- config/dev/spm/sku/sival/01.hsm_offline.hjson
- config/dev/spm/sku/sival/BUILD.bazel
- config/dev/spm/sku/sival/hsm_offline_init.sh
- config/dev/spm/sku/sival/hsm_spm_init.sh
- config/dev/token_init.sh
Split offline and SPM HSM initialization scripts. Each script takes an input (-i) and an output (-o) argument to facilitate sharing of files between HSM initialization stages.
This script also adds bazel targets to package the scripts and their dependencies into tar files.
> [dev] split offline/spm HSM init scripts.

- src/proxy_buffer/store/BUILD.bazel
- src/proxy_buffer/store/connector.go
- src/proxy_buffer/store/db.go
- src/proxy_buffer/store/db_fake.go
- src/proxy_buffer/store/db_test.go
- src/proxy_buffer/store/filedb.go
- src/proxy_buffer/store/filedb_test.go
These methods allow provide functionality to access records that are in an `UNSYNCED` state and to mark said records as SYNCED. This is in preparation to support syncing records into an external registry.
I also added function `filedb.Close()` to close a connection and made tests in `filedb_test.go` independent of each other (each one has their own database now).
> Add store methods to sync unsynced records

- .gitattributes
- README.md
- third_party/lowrisc/ot_bitstreams/README.md
- third_party/lowrisc/ot_bitstreams/build-ot-bitstreams.sh
- third_party/lowrisc/ot_bitstreams/cp_cw340.bit
- third_party/lowrisc/ot_bitstreams/cp_hyper310.bit
- third_party/lowrisc/repos.bzl
This fixes #53 by adding the (updated) FPGA bitstreams using Git LFS.
> [bitstreams] track bitstreams with Git LFS and update them in the process

- src/pa/services/pa_test.go
- src/proxy_buffer/proto/proxy_buffer.proto
- src/proxy_buffer/services/BUILD.bazel
- src/proxy_buffer/services/proxybuffer.go
- src/proxy_buffer/services/proxybuffer_test.go
This method allows us to register multiple devices in a single request.
I also added a new field in DeviceRegistrationResponse: a RPC status code.
> Add support for ProxyBufferServer BatchRegisterDevice

- run_integration_tests.sh
- third_party/lowrisc/ot_fw/BUILD.bazel
- util/integration_test_setup.sh
This moves the integration test setup code that builds and deploys the provisioning infrastructure to a separate shell script so it can be reused between different integration test scripts. In a follow up PR, reference test program integration test scripts will be written to test E2E provisioning flows on the FPGA.
> [tests] move integration test setup code to separate script

- src/proto/device_testdata.go
- src/proxy_buffer/syncer/BUILD.bazel
- src/proxy_buffer/syncer/syncer.go
- src/proxy_buffer/syncer/syncer_test.go
This worker is used to sync records present in the database into the provided registry. It will periodically retrieve all unsynced records from the database, then send them to the registry in a batch request. Only the successful records will be listed as synced, the other ones will be retried in a later run.
This worker runs in the background as a goroutine and can be configured to run with different frequency and records per run.
> Create syncer job between database and registry

- config/deploy.sh
The self hosted github runner was failing to remove configuration files from previous runs due to impromper permissions.
> [github] fix self hosted runner cleanup

- config/prod/spm/sku_sival.yml
- docs/hsm.md
- rules/hsm.bzl
Update the hsm.md document to reflect the current implementation, which splits the offline and SPM configuration steps.
Also, update the `hsm_sku_wrapping_key()` key policy to work with Thales HSMs. Inserted a TODO to revisit the configuration later.
Fixes https://github.com/lowRISC/opentitan-provisioning/issues/110.
> [hsm] Document HSM configuration flow.

- src/proto/device_id.proto
- src/utils/BUILD.bazel
- src/utils/devid.go
- src/utils/devid_test.go
Introduce `devid` package with support for DeviceID operations. This includes having the ability to generate a Device ID proto message from a raw or hex bytes representation of the device ID.
> [utils] Add device id utility functions.

- config/prod/spm/sku_sival.yml
Use RsaPkcsOaep in production mode to be able to unwrap keys with Thales HSMs.
> [config/prod] Update RMA wrapping mechanism

- src/proxy_buffer/services/BUILD.bazel
- src/proxy_buffer/services/http_registry.go
- src/proxy_buffer/services/http_registry_test.go
- src/proxy_buffer/syncer/BUILD.bazel
This PR introduces an implementation of an HTTP registry. This client uses custom intermediate types to pass from the server response (JSON) into proxy_buffer
protos.
I also fixed a visiblity rule in src/proxy_buffer/syncer.
> Create client HTTP registry

- src/ate/test_programs/otlib_wrapper/src/lib.rs
- third_party/lowrisc/ot_bitstreams/build-ot-bitstreams.sh
- third_party/lowrisc/ot_bitstreams/cp_hyper310.bit
- third_party/lowrisc/ot_bitstreams/cp_hyper340.bit
- third_party/lowrisc/ot_fw/build-orch-zip.sh
- third_party/lowrisc/ot_fw/orchestrator.zip
- third_party/lowrisc/repos.bzl
This bumps the lowrisc_opentitan repo version and regenerates the required static assets from said repo including:
1. bitstreams
2. orchestrator.zip
> [opentitan] bump lowrisc_opentitan repo version

- src/proxy_buffer/services/BUILD.bazel
- src/proxy_buffer/services/http_registry.go
- src/testing/fake_registry/BUILD.bazel
- src/testing/fake_registry/README.md
- src/testing/fake_registry/fake_registry.go
This registry is used for E2E testing when a real registry cannot be used.
This PR also changes the error response type in the real registry implementation to gRPC code, which supports unmarshal with both string and numeric codes.
In a follow-up CL I'll integrate this fake registry in the CI tests.
> Create fake HTTP registry

- src/ate/test_programs/cp.cc
The sku C string was getting corrupted and causing the wrong SKU string to be passed to the PA resulting in an integration test error.
> [cp] fix memory bug in CP test program

- src/ate/ate_api.h
- src/ate/ate_dll.cc
Updates the `endorse_cert_request_t` data structure to include the `key_label` and `tbs` bytes as opposed to just pointers to the raw data.
Applies the same change to the `endorse_cert_response_t` data structure.
This is done to simplify the implementation of DUT serialization functions.
> [ate] Refactor EndorseCerts request and response parameters.

- src/proxy_buffer/pb_server.go
- src/proxy_buffer/services/http_registry.go
- src/proxy_buffer/services/http_registry_test.go
This change introduces a new way of passing configuration to the HTTP Registry client. A JSON file can be passed with all the relevant configuration. I also included a wrapper constructor which takes a JSON file path and it will handle the reading and parsing.
I also updated the flags in ProxyBuffer server, as the previous ones are now irrelevant.
> Add JSON configuration for HTTPRegistry

- WORKSPACE
- run_integration_tests.sh
- src/ate/test_programs/otlib_wrapper/src/lib.rs
- third_party/lowrisc/ot_bitstreams/build-ot-bitstreams.sh
- third_party/lowrisc/ot_bitstreams/cp_hyper310.bit
- third_party/lowrisc/ot_bitstreams/cp_hyper340.bit
- third_party/lowrisc/ot_fw/build-orch-zip.sh
- third_party/lowrisc/ot_fw/orchestrator.zip
- third_party/lowrisc/repos.bzl
- util/integration_test_setup.sh
This bumps the lowrisc_opentitan version tag and rebuilds the firmware / bitstreams to match.
> [bazel] bump lowrisc_opentitan version

- config/deploy.sh
- config/dev/containers/provapp.yml.tmpl
- config/dev/containers/registry_config.json.tmpl
- config/dev/env/spm.env
- release/BUILD.bazel
- src/testing/fake_registry/BUILD.bazel
- src/testing/fake_registry/fake_registry.go
- util/containers/deploy_test_k8_pod.sh
This makes use of the fake_registry binary to start a registry in the CI workflow. It configures everything needed for it (the container and the configuration for pb_server to talk to it).
Prod CI workflow integration will come in a later commit.
> Enable registry in dev CI workflow

- config/dev/spm/sku/sival/BUILD.bazel
- config/prod/spm/sku/sival/BUILD.bazel
- config/token_init.sh
- docs/KeyPolicies.md
- docs/hsm.md
- rules/hsm.bzl
- rules/scripts/hsm_ca_sign.sh
- rules/scripts/hsmtool_runner.template.sh
- run_integration_tests.sh
This commit refactors the HSM rules as follows:
* `offline_init`: Generates RMA high and low security seeds as well as
CA root keys.
* `offline_export`: Exports RMA public wrapping (i.e. Public) key.
* `spm_sku_init`: Imports RMA publick key, as well as high and low security
seeds. Only required when sharing seeds across SPM environments.
* `spm_ca_keygen`: Generates Intermediate CA (ICA) certificates for a
particular SKU.
The `hsm_certgen_tar` rule implements CSR export and certificate signing
functionality. See `token_init.sh` for examples. The following targets
where added to support certgen operations:
* `ca_root_certgen`: Generates root CA certificate. Expected to target
an offline HSM.
* `ca_intermediate_certgen`: Generates ICA certificate.
* SPM: Run in CSR export mode.
* Offline: …
> [hsm] Split certificate CSR and signing operations.

- src/proxy_buffer/syncer/syncer_test.go
Fixes //src/proxy_buffer/syncer:syncer_test flakiness issue.
`GetUnsyncedDevices` does not return a consistent device record order. This change sorts the slices before performing comparisons against expected values.
> [pb] Sort unsyced records before comparison check in syncer_test

- src/spm/services/BUILD.bazel
- src/spm/services/skumgr/BUILD.bazel
- src/spm/services/skumgr/skumgr.go
- src/spm/services/spm.go
Move SKU configuration and SE initialization into a separate module (skumgr.go). This enables the loading of a SKU into an SE instance without having to initialize the SPM gRPC service, allowing the SKU and HSM connection to be used in test and utility programs.
The skumgr connection will be used in a follow up commit to implement a TBS certificate generation utility which will enable loadtest and unittests of across all SKU configurations.
> [spm] Refactor SKU management.

- config/spm/sku/sival/ca_int_dice.conf
- config/spm/sku_cr01.yml.tmpl
- config/spm/sku_pi01.yml.tmpl
- config/spm/sku_sival.yml.tmpl
- config/spm/sku_ti01.yml.tmpl
- run_integration_tests.sh
- src/ate/test_programs/ft.cc
- src/pa/BUILD.bazel
- src/pa/loadtest.go
- src/spm/services/se.go
- src/spm/services/se_pk11.go
- src/spm/services/se_pk11_test.go
- src/spm/services/skumgr/skumgr.go
- src/spm/services/spm.go
- src/spm/services/testutils/BUILD.bazel
- src/spm/services/testutils/tbsgen.go
- src/transport/grpconn.go
- util/containers/deploy_test_k8_pod.sh
The following changes are included in this pull request:
- Implement `tbsgen` package to generate Device Under Test (DUT) To-Be-Signed (TBS) certificates. The TBS results in correct certificate chain verification after signed by the SPM. 
- Implement certificate verification inside `EndorseCerts`. The certs are not returned to the caller unless valid.
- Update test cases to cover new functionality.
> [spm] Verify certificate chain before returning each cert in `EndorseCerts` API

- util/integration_test_setup.sh
Kill the SPM progress subgroup. This is necessary because the bazel command spawns a child process for the SPM server.
> [test] Fix integration test hang

- src/ate/test_programs/cp.cc
- src/ate/test_programs/dut_lib/BUILD.bazel
- src/ate/test_programs/dut_lib/dut_lib.cc
- src/ate/test_programs/dut_lib/dut_lib.h
- src/ate/test_programs/otlib_wrapper/src/lib.rs
This refactors the console RX method to be able to RX several SPI console frames in a single call. This will be required to RX UJSON payloads like the perso blob which spans several SPI console frames.
> [dut_lib] enable console RX of several SPI frames

- config/spm/sku_auth.yml.tmpl
- src/ate/ate_api.h
- src/ate/ate_api_json_commands.cc
- src/ate/ate_api_json_commands_test.cc
- src/ate/ate_client.cc
- src/ate/ate_client.h
- src/ate/ate_dll.cc
- src/ate/proto/dut_commands.proto
- src/ate/test_programs/ft.cc
- src/pa/loadtest.go
- src/pa/proto/pa.proto
- src/pa/services/pa.go
- src/pa/services/pa_test.go
- src/spm/proto/spm.proto
- src/spm/services/spm.go
This replaces the `GetCaSerialNumbers` for `GetCaSubjecKeys`. This is to allow Intermediate CA (ICA) certificates to have a serial number set to a value different than its SubjectKeyId. openssl doesn't set the serial number to the SubjectKeyId by default.
The ICA SubjectKeyId is used by the DUT to populate the AuthorityKeyID. Below is a sample SPM log after applying the change in this commit:
```console
2025/06/08 20:43:14 DUT cert AuthorityKeyID: ff12c119c25880fefa2ff765551aef255c0c5622
2025/06/08 20:43:14 DUT cert Issuer: CN=Google Engineering ICA,OU=Engineering,O=Google,ST=CA,C=US
2025/06/08 20:43:14 ICA SubjectKeyID: ff12c119c25880fefa2ff765551aef255c0c5622
2025/06/08 20:43:14 ICA Subject: CN=Google Engineering ICA,OU=Engineering,O=Google,ST=CA,C=US
```
> [spm] Export ICA SubjectKeyId

- src/ate/BUILD.bazel
- src/ate/ate_api.h
- src/ate/ate_dll.cc
This removes the include of an autogenerate protobuf header file from the ate_api.h header file.
> [ate_dll] remove autogenerated proto header dep

- src/pa/loadtest.go
- src/spm/services/se_pk11.go
- src/spm/services/se_pk11_test.go
This change enables the WAS to be able to run it with the device firmware.
The SPM server was updated to handle the HMAC key in the byte order handled by the device.
> [spm] Enable WAS end-2-end test.

- docs/deployment.md
This is required to build the configuration files required to deploy infrastructure services, as well as the HSM configuration scripts.
> [docs] Add instructions on how to build the config bundle.

- src/ate/BUILD.bazel
- src/proto/device_id.proto
This has two commits that:
1. adds the Earlgrey A2 silicon product ID code, and
2. adds compiler configurations to the ATE libs.
> [proto,ate] add A2 silicon product ID and add compiler configurations

- .bazelrc
- config/spm/sku/eg/common/BUILD.bazel
- rules/hsm.bzl
- src/ate/test_programs/ft.cc
- third_party/lowrisc/ot_bitstreams/build-ot-bitstreams.sh
- third_party/lowrisc/ot_bitstreams/cp_hyper310.bit
- third_party/lowrisc/ot_bitstreams/cp_hyper340.bit
- third_party/lowrisc/ot_fw/build-orch-zip.sh
- third_party/lowrisc/ot_fw/orchestrator.zip
- third_party/lowrisc/repos.bzl
- util/airgapped_builds/prep-bazel-airgapped-build.sh
There are two versions of the vendor-specific AES key wrapping mechanism:
1. VendorThalesAesKw, and
2. VendorThalesAesKwp.
The former is only capatible with keys that are multiples of 64-bits, while the latter is compatible across all key sizes ("p" stands for padded version). However, only the former (VendorThalesAesKw) is supported between specific version of the HSM we have deployed. Therefore we reconfigure the prod deployment to use this key wrapping/unwrapping mechanism.
Note, when using the VendorThalesAesKw mechanism, it is imparative the `CKA_VALUE_LEN` attribute is set when importing a wrapped secret into the HSM.
Note: this depends on #224; only review the last commit.
> [hsm] use backwards compatible key wrap mechanism

- src/ate/test_programs/ft.cc
Use `endorsed_x509_certs` when calling `PackPersoBlob` to send the certificates endorsed by the SPM back to the DUT.
> [ate] Update ft.cc PackPersoBlob arguments.

- src/ate/ate_dll.cc
Explicitly check the `ate_client` static pointer inside the ate_dll.cc module before casting and destroying the obfuscated pointer passed by the caller.
> [ate] Check ate_client pointer in DestroyClient call.

- rules/hsm.bzl
The patching of the PKCS#11 attributes to include the `CKA_VALUE_LEN` attribute when the `VendorThalesAesKw` mechanism is used was not propagating through the bazel configuration rules properly.
> [bazel] fix hsmtool config script generation

- src/ate/ate_api.h
- src/ate/ate_client.cc
- src/ate/ate_dll.cc
- src/ate/test_programs/cp.cc
- src/ate/test_programs/ft.cc
- Explicitly call PA stub constructor in `AteClient::Create` call.
- Add return error code to ATE DLL `CreateClient` API to improve error handling.
> [ate] Explicitly create PA stub.

- src/ate/ate_dll.cc
- src/ate/test_programs/ft.cc
- src/pa/loadtest.go
- src/spm/services/spm.go
- src/spm/services/testutils/tbsgen.go
This change introduces shorter, more stable aliases for certificate key labels used in the provisioning process. The aliases "UDS" (Unique Device Secret) and "EXT" (Extension) are now used by client applications.
The SPM service is responsible for mapping these aliases to the underlying key labels ("SigningKey/Dice/v0" and "SigningKey/Ext/v0"). This provides a layer of abstraction, making the client-side implementation cleaner and less coupled to the internal naming scheme.
Key changes:
- `spm`: Translates "UDS" and "EXT" labels to their full counterparts during key retrieval and certificate endorsement. It now gracefully handles missing certificates by returning an empty subject key.
- `ate`: The client library now accepts the key label directly from the caller instead of hardcoding a …
> [spm] Introduce UDS/EXT aliases for certificate key labels

- docs/ate.md
- run_integration_tests.sh
- src/ate/ate_api.h
- src/ate/ate_client.cc
- src/ate/ate_client.h
- src/ate/ate_dll.cc
- src/ate/test_programs/cp.cc
- src/ate/test_programs/ft.cc
This change introduces gRPC client-side load balancing to the ATE client library and documents its usage.
ATE Client Library:
- The client options now accept a `pa_target` in gRPC name-syntax format (e.g., "ipv4:host1:port,host2:port") to enable connecting to multiple server instances.
- A `load_balancing_policy` option has been added to allow callers to select policies like "round_robin".
- The client creation logic was updated to use `grpc::CreateCustomChannel` to apply the specified load balancing configuration.
- Test programs and integration test scripts were updated to use the new `--pa_target` and `--load_balancing_policy` flags.
Documentation (`docs/ate.md`):
- Added a section on "Client-Side Load Balancing and Failover," explaining how to configure it and what to expect during …
> [ate]: Enable client-side load balancing and update docs

- src/ate/ate_api.h
- src/ate/ate_perso_blob.cc
- src/ate/ate_perso_blob.h
- src/ate/ate_perso_blob_test.cc
- src/ate/test_programs/ft.cc
The personalization firmware includes the hash of itself in the perso blob it sends to the host. We update the ATE DLL to parse this data and write it to the registry along with the other DUT data.
Note: this depends on #237; only review the last commit.
> [ate] extract personalization FW hash from perso blob

- config/containers/provapp.yml.tmpl
- config/env/dev/spm.env
- config/env/prod/spm.env
- docs/ate.md
- run_integration_tests.sh
- src/ate/ate_api.h
- src/ate/ate_client.cc
- src/ate/ate_dll.cc
This commit refactors the ATE client library to remove the singleton pattern to enable downstream users to manage multiple client instances.
Previously, `CreateClient` would always return the same client instance, making it impossible to connect to multiple, distinct provisioning servers from a single application. The singleton implementation also had a potential race condition in the `CreateClient` call.
This change introduces the following:
- The `ate_dll.cc` no longer uses a static client. Each call to `CreateClient` now returns a new, independent client instance.
- Callers are now responsible for managing the lifecycle of each client and must call `DestroyClient` for every instance created.
- The documentation in `ate_api.h` and `ate.md` has been updated to reflect the new factory …
> [ate]: Remove client singleton and support multiple instances

- src/pa/services/pa.go
- src/spm/services/se_pk11.go
- src/spm/services/se_pk11_test.go
- src/spm/services/spm.go
The `se_pk11` package was returning a raw ECDSA public key, which caused parsing failures in the SPM. This change updates the implementation to return the public key in the standard `SubjectPublicKeyInfo` format by using `x509.MarshalPKIXPublicKey`.
This fixes ASN.1 parsing errors and ensures interoperability. The updated key format is now correctly handled when endorsing data and generating certificates.
This change also updates the EndorseData parameters to use P256-SHA256 instead of P384-SHA384. This is to match the SPM identity key configuration used in the HSMs.
> [spm]: Update EndorseData public key format

- src/ate/ate_api.h
- src/ate/ate_dll.cc
- src/ate/ate_perso_blob.cc
- src/ate/test_programs/ft.cc
The personalization firmware can produce DUT-endorsed X.509 or CWT certificates depending on the SKU. This updates the ATE DLL to unpack CWT certs, in addition to the X.509 certs, so they will be included in the TLV data structure written to the device registry.
> [ate] unpack CWT certs to push to registry

- src/ate/BUILD.bazel
- src/ate/perso_blob.go
- src/ate/perso_blob_test.go
perso_blob.go is part of the ate package. It contains Go versions of the `ate_perso_blob.cc` implementation. This is done to avoid adding cgo dependencies.
> [ate] Add perso_blob Go package.

- config/spm/sku_auth.yml.tmpl
- config/spm/sku_cr01.yml.tmpl
- config/spm/sku_pi01.yml.tmpl
- config/spm/sku_sival.yml.tmpl
- config/spm/sku_ti01.yml.tmpl
- src/ate/ate_api.h
- src/ate/ate_client.cc
- src/ate/ate_client.h
- src/ate/ate_dll.cc
- src/ate/test_programs/dut_lib/dut_lib.cc
- src/ate/test_programs/dut_lib/dut_lib.h
- src/ate/test_programs/ft.cc
- src/ate/test_programs/otlib_wrapper/src/lib.rs
- src/pa/proto/pa.proto
- src/pa/services/pa.go
- src/pa/services/pa_test.go
- src/spm/proto/spm.proto
- src/spm/services/skucfg.go
- src/spm/services/spm.go
After personalization completes, to confirm everything completed successfully, we reset the DUT and wait for the ROM_EXT and Owner firmware to boot, by waiting for a message to appear over the UART.
> [ate,pa,spm,dut_lib] add ROM_EXT and owner FW boot check

- src/ate/ate_api.h
- src/ate/ate_api_json_commands.cc
- src/ate/ate_api_json_commands_test.cc
- src/ate/test_programs/cp.cc
- src/ate/test_programs/dut_lib/dut_lib.cc
- src/ate/test_programs/dut_lib/dut_lib.h
- src/ate/test_programs/ft.cc
- src/ate/test_programs/otlib_wrapper/src/lib.rs
Previously, we used one struct type for sending data to / from the DUT over the SPI console. However, the size of a SPI console data frame that is TXed by the DUT to the ATE is a maximum size of 2020 bytes, while the size of a SPI console data frame that is RXed by the DUT from the ATE is a maximum size of 256 bytes.
Therefore, we add a struct to represent a SPI console frame that is RXed by the DUT too to facilitate ATE integrations.
Thanks @BenBenderOT for pointing this out!
> [ate] add separate SPI frame buffers for DUT TX and RX directions

- README.md
Move install references to install block, and add additional details on how to pull LFS resources if the repo was cloned before LFS was initialized in the target machine.
> [doc] Update LFS instructions.

- src/pa/services/pa.go
- src/pa/services/pa_test.go
- src/spm/services/spm.go
This commit introduces several improvements to error handling and logging in the SPM and PA services.
In the Provisioning Appliance (PA):
- Replaced generic internal error statuses with the specific status codes returned by the SPM. This provides more meaningful error information to the client.
- Enhanced log messages to include the SKU, which aids in debugging and tracing requests for specific device types.
In the Secure Provisioning Module (SPM):
- Corrected gRPC status codes to more accurately reflect the nature of the error. For example, using `NotFound` for unknown SKUs and `Unauthenticated` for failed authentication instead of `Internal`.
- Made error messages more descriptive by including contextual information such as the SKU, which helps in diagnosing issues.
- Changed several …
> [pa/spm] Improve SPM and PA error handling and logging

- src/ate/ate_api.h
- src/ate/ate_api_json_commands.cc
- src/ate/ate_api_json_commands_test.cc
- src/ate/test_programs/cp.cc
- src/ate/test_programs/dut_lib/dut_lib.cc
- src/ate/test_programs/dut_lib/dut_lib.h
- src/ate/test_programs/ft.cc
- src/ate/test_programs/otlib_wrapper/src/lib.rs
This consolidates the `dut_rx_spi_frame_t` and `dut_tx_spi_frame_t` types into a single `dut_spi_frame_t` type. While SPI frames received from the DUT may be different sizes, SPI frames sent to the DUT are fixed to a size of 256 bytes.
> [ate] consolidate `dut_*_spi_frame_t` types

- src/proto/validators.go
Earlgrey A2 product ID is a valid product ID.
> [validators] add missing product ID

- config/spm/sku_cr01.yml.tmpl
- config/spm/sku_pi01.yml.tmpl
- config/spm/sku_sival.yml.tmpl
- config/spm/sku_ti01.yml.tmpl
- src/ate/ate_api.h
- src/ate/ate_api_json_commands.cc
- src/ate/ate_dll.cc
- src/ate/ate_perso_blob.cc
- src/ate/ate_perso_blob_test.cc
- src/ate/perso_blob.go
- src/ate/proto/dut_commands.proto
- src/ate/test_programs/ft.cc
- src/pa/loadtest.go
- src/pa/proto/BUILD.bazel
- src/pa/proto/pa.proto
- src/pa/services/pa.go
- src/spm/proto/BUILD.bazel
- src/spm/proto/spm.proto
- src/spm/services/skucfg.go
- src/spm/services/spm.go
After writing all certificates to flash, the DUT reads out each certificate and computes a SHA256 hash over them. It then sends this hash to the host so the provisioning-infrastructure can validate the certificates were installed successfully into non-volatile storage on the DUT.
To validate this hash, we update the RegisterDevice API to validate the hash of all certs written to flash.
> [pa,spm,ate] add scaffolding to verify hash of all certs

- src/ate/ate_api.h
- src/ate/ate_dll.cc
- src/ate/test_programs/ft.cc
This fixes win32 compilation errors (the ATE DLL must build in such an environment). This also adds a parameter to the RegisterDevice function to pass raw ATE data.
> [ate] fix win32 compilation errors

- src/ate/version.rc
This bumps the ATE DLL release version to 2.0.0.0 to reflect the first release / deployment.
> [ate] bump ATE DLL version to 2.0.0.0

- src/proto/device_id_utils.go
There were several bugs in the device ID to hextstring util:
1. Si Creator ID should be 16 bits not 32.
2. Product ID should be 16 bits not 32.
3. SKU specific field should be 128 bits.
> [device_id] fix device ID string formatting util

- src/utils/utils.go
- util/rr_parser/BUILD.bazel
- util/rr_parser/rr_parser.go
This change enhances the `rr_parser` utility with capabilities to parse, process, and verify certificates from registry records.
Key updates include:
- New data structures and functions for certificate handling.
- A rewritten `main` function to orchestrate the new certificate handling and verification workflow.
- Integration with `openssl` for certificate verification.
Other changes:
The `BlobToPEMString` function in `src/utils/utils.go` has been renamed to `DERCertToPEMString` to more accurately reflect its functionality.
The `BUILD.bazel` file for `rr_parser` has been updated to include a necessary dependency on `//src/utils`.
> [rr_parser]: Add certificate parsing and verification

- src/spm/services/se_pk11.go
- src/spm/services/testutils/tbsgen.go
The `TokenTypeKeyGen` in `GenerateTokens()` generates an emphemeral key which is exported in wrapped form. This change deletes the object from the HSM memory after it is no longer needed.
> [spm] Clear ephemeral keys from memory in GenerateTokens.

- run_integration_tests.sh
- src/ate/ate_api.h
- src/ate/ate_client.cc
- src/ate/ate_client.h
- src/ate/ate_dll.cc
- src/ate/ate_perso_blob.cc
- src/ate/ate_perso_blob_test.cc
- src/ate/test_programs/ft.cc
- third_party/lowrisc/ot_bitstreams/build-ot-bitstreams.sh
- third_party/lowrisc/ot_bitstreams/cp_hyper310.bit
- third_party/lowrisc/ot_bitstreams/cp_hyper340.bit
- third_party/lowrisc/ot_fw/build-orch-zip.sh
- third_party/lowrisc/ot_fw/orchestrator.zip
- util/integration_test_setup.sh
This updates the reference FT test program to retrieve the CA certs from the SPM during perso to facilitate SKUs (i.e., pi01/2) that require passing the root and ICA certs to the DUT during perso.
> [ft] get CA certs from SPM during perso
